context:
  version: "1.97.0"

package:
  name: litellm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/litellm/litellm-${{ version }}.tar.gz
  sha256: 6f7ce326a2e5385ef850e0b0768d41f502ec79278860090a838511cea067b067

build:
  skip:
    - match(python, "<3.11")
    - match(python, ">3.14")
  script:
    - cd litellm-rust
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cd ..
    - python -m pip install . -vv
  number: 1
  python:
    entry_points:
      - litellm = litellm:run_server

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin ==1.9.4
        - pip
  host:
    - maturin ==1.9.4
    - pip
    - puccinialin
    - python
  run:
    - pydantic-settings >=2.14.1,<3.0
    - fastuuid >=0.14.0,<1.0
    - httpx >=0.28.0,<1.0
    - python
    - openai >=2.20.0,<3.0.0
    - python-dotenv >=1.0.0,<2.0
    - tiktoken >=0.8.0,<1.0
    - importlib-metadata >=8.0.0,<9.0
    - tokenizers >=0.21.0,<1.0
    - click >=8.0.0,<9.0
    - jinja2 >=3.1.6,<4.0
    - aiohttp >=3.14.2,<4.0
    - pydantic >=2.10.0,<3.0.0
    - pydantic-settings >=2.14.1,<3.0
    - jsonschema >=4.0.0,<5.0

tests:
  - python:
      imports: litellm
      pip_check: true
  - script: litellm --help

about:
  homepage: https://www.litellm.ai
  summary: 'Library to easily interface with LLM API providers'
  license: MIT
  license_file:
    - LICENSE
    - litellm-rust/THIRDPARTY.yml
  documentation: https://docs.litellm.ai
  repository: https://github.com/BerriAI/litellm

extra:
  recipe-maintainers:
    - m-rossi
    - jan-janssen
